    antigravity
    
    Revisão do módulo financeiro

diff --git a/supabase/functions/import-historico-axis/index.ts b/supabase/functions/import-historico-axis/index.ts
deleted file mode 100644
index dbfdfb5..0000000
--- a/supabase/functions/import-historico-axis/index.ts
+++ /dev/null
@@ -1,252 +0,0 @@
-import { createClient } from "npm:@supabase/supabase-js@2";
-
-const corsHeaders = {
-  "Access-Control-Allow-Origin": "*",
-  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
-};
-
-const EXTERNAL_PROJECT_URL = "https://pyexbnnuzjcsiypootcq.supabase.co";
-
-function parseDate(ddmmyyyy: string): string | null {
-  if (!ddmmyyyy) return null;
-  const parts = ddmmyyyy.split("/");
-  if (parts.length !== 3) return null;
-  const [dd, mm, yyyy] = parts;
-  return `${yyyy}-${mm.padStart(2, "0")}-${dd.padStart(2, "0")}`;
-}
-
-function parsePeso(peso: string): number {
-  if (!peso) return 1;
-  const num = parseFloat(peso.replace("%", "").replace(",", ".").trim());
-  if (isNaN(num) || num <= 0) return 1;
-  return Math.max(1, Math.round(num / 100));
-}
-
-Deno.serve(async (req) => {
-  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
-
-  try {
-    const body = await req.json().catch(() => ({}));
-
-    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
-    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
-    const externalKey = body.external_key || Deno.env.get("EXTERNAL_SUPABASE_SERVICE_KEY");
-
-    if (!externalKey) {
-      return new Response(
-        JSON.stringify({ error: "EXTERNAL_SUPABASE_SERVICE_KEY not configured" }),
-        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
-      );
-    }
-
-    const local = createClient(supabaseUrl, supabaseKey);
-    const external = createClient(EXTERNAL_PROJECT_URL, externalKey);
-
-    const batchSize = body.batch_size || 500;
-    const startOffset = body.offset || 0;
-
-    // Load lookup tables from LOCAL project
-    const { data: profiles } = await local
-      .from("profiles")
-      .select("user_id, full_name");
-
-    const { data: actTypes } = await local
-      .from("activity_types")
-      .select("id, name")
-      .eq("is_active", true);
-
-    // Load processes in pages to bypass 1000 default limit
-    let allProcesses: any[] = [];
-    let pOffset = 0;
-    const pSize = 5000;
-    while (true) {
-      const { data: pBatch } = await local
-        .from("processes")
-        .select("id, numero_processo")
-        .range(pOffset, pOffset + pSize - 1);
-      if (!pBatch || pBatch.length === 0) break;
-      allProcesses = allProcesses.concat(pBatch);
-      if (pBatch.length < pSize) break;
-      pOffset += pSize;
-    }
-
-    // Build lookup maps (case-insensitive)
-    const profileMap = new Map<string, string>();
-    profiles?.forEach((p: any) => {
-      const normalized = p.full_name?.toUpperCase()?.trim()?.normalize("NFD")?.replace(/[\u0300-\u036f]/g, "");
-      if (normalized) profileMap.set(normalized, p.user_id);
-    });
-
-    const actTypeMap = new Map<string, string>();
-    actTypes?.forEach((a: any) => {
-      const normalized = a.name?.toUpperCase()?.trim()?.normalize("NFD")?.replace(/[\u0300-\u036f]/g, "");
-      actTypeMap.set(normalized, a.id);
-    });
-
-    // Aliases for activity names that differ between external and local data
-    const activityAliases: Record<string, string> = {
-      "CALCULO SEGUNDA HIPOTESE": "CALCULO DE SEGUNDA HIPOTESE",
-    };
-    for (const [alias, canonical] of Object.entries(activityAliases)) {
-      const id = actTypeMap.get(canonical);
-      if (id) actTypeMap.set(alias, id);
-    }
-
-    const processMap = new Map<string, string>();
-    allProcesses.forEach((p: any) => {
-      if (p.numero_processo) {
-        processMap.set(p.numero_processo.replace(/\s+/g, "").trim(), p.id);
-      }
-    });
-
-    console.log(`Lookup: ${profileMap.size} profiles, ${actTypeMap.size} activity_types, ${processMap.size} processes`);
-
-    const stats = {
-      total: 0,
-      inserted: 0,
-      skipped_no_user: 0,
-      skipped_no_date: 0,
-      duplicates: 0,
-      errors: 0,
-      unmatched_users: new Set<string>(),
-      unmatched_activities: new Set<string>(),
-    };
-
-    let offset = startOffset;
-    let hasMore = true;
-    const SAFETY_TIMEOUT = 50_000;
-    const startTime = Date.now();
-
-    while (hasMore) {
-      if (Date.now() - startTime > SAFETY_TIMEOUT) {
-        console.log(`Safety timeout at offset ${offset}`);
-        break;
-      }
-
-      // Read from EXTERNAL project
-      const { data: rows, error } = await external
-        .from("historico_axis")
-        .select("*")
-        .range(offset, offset + batchSize - 1);
-
-      if (error) {
-        console.error("External fetch error:", error.message);
-        break;
-      }
-      if (!rows || rows.length === 0) {
-        hasMore = false;
-        break;
-      }
-
-      const inserts: any[] = [];
-
-      for (const row of rows as any[]) {
-        stats.total++;
-
-        const profName = row.profissional?.toUpperCase()?.trim()?.normalize("NFD")?.replace(/[\u0300-\u036f]/g, "");
-        const userId = profileMap.get(profName);
-        if (!userId) {
-          stats.skipped_no_user++;
-          if (profName) stats.unmatched_users.add(profName);
-          continue;
-        }
-
-        const dataAtividade = parseDate(row.lancamento);
-        if (!dataAtividade) {
-          stats.skipped_no_date++;
-          continue;
-        }
-
-        const procNum = row.numero_processo?.replace(/\s+/g, "")?.trim();
-        const processId = procNum ? processMap.get(procNum) : null;
-
-        const actName = row.tipo_atividade?.toUpperCase()?.trim()?.normalize("NFD")?.replace(/[\u0300-\u036f]/g, "")?.replace(/ELABORARACAO/g, "ELABORACAO");
-        const activityTypeId = actName ? actTypeMap.get(actName) : null;
-        if (actName && !activityTypeId) {
-          stats.unmatched_activities.add(actName);
-        }
-
-        const quantidade = parsePeso(row.peso);
-        const descricao = (row.descritivo || "").trim();
-        const reclamanteNome = (row.parte_contraria || "").trim().toUpperCase();
-
-        inserts.push({
-          user_id: userId,
-          process_id: processId,
-          activity_type_id: activityTypeId,
-          data_atividade: dataAtividade,
-          descricao,
-          reclamante_nome: reclamanteNome || null,
-          quantidade,
-        });
-      }
-
-      // Batch insert into LOCAL project
-      if (inserts.length > 0) {
-        for (let i = 0; i < inserts.length; i += 50) {
-          const batch = inserts.slice(i, i + 50);
-          const { error: upsertErr } = await local
-            .from("timesheet_entries")
-            .upsert(batch, {
-              onConflict: "user_id,COALESCE(process_id::text, ''),COALESCE(activity_type_id::text, ''),data_atividade,descricao,COALESCE(reclamante_nome, '')",
-              ignoreDuplicates: true,
-            });
-
-          if (upsertErr) {
-            for (const entry of batch) {
-              const { error: singleErr } = await local
-                .from("timesheet_entries")
-                .insert(entry);
-              if (singleErr) {
-                if (singleErr.message?.includes("duplicate") || singleErr.code === "23505") {
-                  stats.duplicates++;
-                } else {
-                  stats.errors++;
-                  if (stats.errors <= 5) console.error("Insert err:", singleErr.message);
-                }
-              } else {
-                stats.inserted++;
-              }
-            }
-          } else {
-            stats.inserted += batch.length;
-          }
-        }
-      }
-
-      console.log(`Batch offset=${offset}, rows=${rows.length}, inserts=${inserts.length}`);
-
-      if (rows.length < batchSize) hasMore = false;
-      else offset += batchSize;
-    }
-
-    const result = {
-      status: "ok",
-      source: "external",
-      next_offset: hasMore ? offset : null,
-      stats: {
-        total: stats.total,
-        inserted: stats.inserted,
-        skipped_no_user: stats.skipped_no_user,
-        skipped_no_date: stats.skipped_no_date,
-        duplicates: stats.duplicates,
-        errors: stats.errors,
-        unmatched_users: [...stats.unmatched_users].slice(0, 30),
-        unmatched_activities: [...stats.unmatched_activities].slice(0, 30),
-      },
-    };
-
-    console.log("Result:", JSON.stringify(result));
-
-    return new Response(JSON.stringify(result), {
-      status: 200,
-      headers: { ...corsHeaders, "Content-Type": "application/json" },
-    });
-  } catch (error: any) {
-    console.error("Fatal error:", error);
-    return new Response(JSON.stringify({ error: error.message }), {
-      status: 500,
-      headers: { ...corsHeaders, "Content-Type": "application/json" },
-    });
-  }
-});
